export {default as category} from './resource/category'
export {default as subcategory} from './resource/subcategory'
export {default as chowkri} from './resource/chowkri'
export {default as account} from './resource/account'
export {default as connectionSize} from './resource/connectionSize'
export {default as slab} from './resource/slab'
export {default as meterStatus} from './resource/meterStatus'
export {default as chargeType } from './resource/chargeType'
export {default as cin} from './resource/cin'
export {default as ownPrivateSupply} from './resource/ownPrivateSupply'
export {default as connectionType} from './resource/connectionType'
export {default as typeProperty} from './resource/typeProperty'
export {default as supplyZone} from './resource/supplyZone'
export {default as paymentBudget} from './resource/paymentBudget'
export {default as tariffConfigure} from './resource/tariffConfigure'
export {default as billAgencyEnrollment} from './resource/billAgencyEnrollment'

